# =============================================================================
# sonbal.conf
# Copyright (c) 2026 Hodong Kim <hodong@nimfsoft.com>
# SPDX-License-Identifier: 0BSD
# =============================================================================

d /var/lib/sonbal-openai 0700 root root -
