# =============================================================================
# sonbal.conf
# Copyright (c) 2026 Hodong Kim <hodong@nimfsoft.com>
# SPDX-License-Identifier: 0BSD
# =============================================================================

u sonbal - "Sonbal execution service" /nonexistent /usr/sbin/nologin
